#!/bin/bash
# changeVolume
 
# Arbitrary but unique message tag
msgTag="myvolume"
 
if [[ "$@" == "toggle" ]]; then
	wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
else
	wpctl set-volume @DEFAULT_AUDIO_SINK@ "$@" 
fi
 
# Query ~~amixer~~ wireplumber for the current volume and whether or not the speaker is muted

if [[ $(wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep "MUTED" ) ]]; then
	notify-send -t 1000 -a "changeVolume" -u low \
	-h string:x-canonical-private-synchronous:${msgTag} "MUTE"
else
	volume=$(expr $(wpctl get-volume @DEFAULT_AUDIO_SINK@ | tr -d -c 0-9) + 0)
	notify-send -t 1000 -a "changeVolume" -u low \
	-h string:x-canonical-private-synchronous:${msgTag} \
	-h int:value:"$volume" "Volume : ${volume}%"
fi
