#!/bin/bash

# chmod +x convert_multiple_files to make it executable

# IFS : defines array separator
# default separator = spacebar (\n)
# but since filename has spacebar, the separator has to be changed
# new separator = line break (\b)
IFS=$'\b'

# declare -a : declares array
# find .m4a files to maximum 6 subdirectories
# separate with line break (\b)
# the elements will be .m4a files (spacebar intact)
declare -a m4as=($(find . -maxdepth 6 -type f -iname '*.m4a' -printf '%p\b'))

for i in "${m4as[@]}"
do
	# new filename replaced .mp4 to .mp3
	mp3=${i/\.m4a/\.mp3}
	# I don't know what ffmpeg does, but spacebar is intact
	ffmpeg -i "$i" -c:v copy -c:a libmp3lame -q:a 4 "${mp3}"
	# remove .m4a file
	rm "$i"
done

# can also be used to convert .pdf to .svg
# pdf2svg "$i" "${svg}" [<page no of pdf or "all">]

