#!/bin/bash

msgTag1="test1"
msgTag2="test2"
msgTag3="test3"
 
notify-send -t 10000 -a "test" -u low \
	-h string:x-canonical-private-synchronous:${msgTag} \
	-h int:value:50 "LOW"

notify-send -t 10000 -a "test" -u normal \
	-h string:x-canonical-private-synchronous:${msgTag} \
	-h int:value:50 "NORMAL"

notify-send -t 10000 -a "test" -u critical \
	-h string:x-canonical-private-synchronous:${msgTag} \
	-h int:value:50 "CRITICAL"
